version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - bot_network
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER:?error}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASS:?error}
  bot:
    build:
      context: ./src
      dockerfile: ./services/Bots/Platform.Telegram.Bot/Dockerfile
    image: vsp/telegram-bot:0.1
    container_name: 'telegram-bot'
    hostname: 'telegram-bot'
    ports:
      - "8000:80"
    networks:
      - bot_network
    environment:
      - Telegram__ApiKey=${API_KEY:?error}
      - Bus__Host=rabbitmq
      - Bus__UserName=${RMQ_USER:?error}
      - Bus__Password=${RMQ_PASS:?error}
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  reporter:
    build:
      context: ./src
      dockerfile: ./services/Consumers/Platform.Consumer.Reporter/Dockerfile
    image: vsp/reporter:0.1
    container_name: 'reporter'
    hostname: 'reporter'
    ports:
      - "8001:80"
    networks:
      - bot_network
    environment:
      - Bus__Host=rabbitmq
      - Bus__UserName=${RMQ_USER:?error}
      - Bus__Password=${RMQ_PASS:?error}
    depends_on:
      - rabbitmq
      - bot
    links:
      - rabbitmq
  collector:
    build:
      context: ./src
      dockerfile: ./services/Consumers/Platform.Consumer.Collector/Dockerfile
    image: vsp/collector:0.1
    container_name: 'collector'
    hostname: 'collector'
    ports:
      - "8002:80"
    networks:
      - bot_network
    environment:
      - Bus__Host=rabbitmq
      - Bus__UserName=${RMQ_USER:?error}
      - Bus__Password=${RMQ_PASS:?error}
    depends_on:
      - rabbitmq
      - bot
    links:
      - rabbitmq
  scanner:
    build:
      context: ./src
      dockerfile: ./services/Consumers/Platform.Consumer.Scanner/Dockerfile
    image: vsp/scanner:0.1
    container_name: 'scanner'
    hostname: 'scanner'
    ports:
      - "8003:80"
    networks:
      - bot_network
    environment:
      - Bus__Host=rabbitmq
      - Bus__UserName=${RMQ_USER:?error}
      - Bus__Password=${RMQ_PASS:?error}
    depends_on:
      - rabbitmq
      - bot
    links:
      - rabbitmq

networks:
  bot_network:
    driver: bridge