#!/bin/bash

ver=0.1

function build_toolkit_image() {
  docker build -f toolkit.Dockerfile -t vsp/toolkit:$ver .
}

function up_local() {
  build_toolkit_image
  docker compose build
  docker compose up
} 

function down_local() {
  docker compose down
}

function clean_local() {
  docker rmi vsp/telegram-bot:$ver vsp/reporter:$ver vsp/collector:$ver vsp/collector:$ver vsp/scanner:$ver
}

function clean_all_local() {
  down_local
  docker rmi vsp/telegram-bot:$ver vsp/reporter:$ver vsp/collector:$ver vsp/collector:$ver vsp/scanner:$ver
  docker rmi vsp/toolkit:$ver
  docker rmi rabbitmq:3.8-management
}

"$@"
